Update mouse navigation
Clinical-Genomics-Lund/gens pull request #31
Opened 2021-02-03 14:03 UTC by mhkc

This PR moves the "select region to zoom in" functionality from the overview canvas to the detailed view. It introduces two new input methods `shift - drag mouse` to zoom in on a selected region and `ctrl - mouse click` to zoom out.

**How to test**:
1. Goto [Gens dev version](http://10.0.224.64:5003/643594?region=8:141468087-141468253&variant=84af935d282baeb23862b3c28670f9f9)
2. Try zooming in on the highlighted variant with `shift - drag mouse`
3. Try zooming out with `ctrl - mouse click`
4. Try navigating between chromosomes by clicking them on the overview canvas

**Expected outcome**:
The new input methods is fully working.

**Review:**
- [ ] code approved by

2021-02-03 14:48 UTC, ViktorHy commented
works like a clock!

2021-02-04 07:00 UTC, bjhall requested changes
The code looks great, I only found some minor bugs.

The biggest one being that jumping directly to a chromosome by pressing for instance 5+Enter seems to be broken. I don't know if this feature is used by anyone? Is it the only reason that the KeyLogger thingy exists?

2021-02-10 10:21 UTC, mhkc commented on gens/static/js/interactive.js
> -          case '+':
Sounds like a good idea

2021-02-10 11:54 UTC, bjhall commented
Looks great! Feel free to merge.

2021-02-10 11:56 UTC, merged